### ISSUE TITLE
invalid_grant after a week ish

### ISSUE THREAD

**Issue by Niklas1191** [No3x/MMM-GoogleDocs-Notes#7] opened 2021-03-02 08:45 UTC
Hello guys.

I have tried this module for about a month now but I have an issue wich are really hard to solv by my own for some reason...
After configuration everything works flawless, the logs look like this;

```
[2021-03-01 01:17:14.931] [LOG]    [MMM-GoogleDocs-Notes] Found 2 documents in drive matching the search {"orderBy":"modifiedTime","q":"mimeType = 'application/vnd.google-apps.document' and name starts with 'NEWS' and trashed = false"}.


[2021-03-01 01:17:14.933] [LOG]    [MMM-GoogleDocs-Notes] noteDocumentId: 1knLd1CDBtcJsybpk1l-1rYZKcyZPZCDwR8yAETcZQdE


[2021-03-01 01:17:14.935] [LOG]    [MMM-GoogleDocs-Notes] noteDocumentId: 1b4hOQ64SilaMuivefAfcZjD7fYooHSPbn_Z3S_irvnM


[2021-03-01 01:17:15.148] [LOG]    [MMM-GoogleDocs-Notes][1knLd1CDBtcJsybpk1l-1rYZKcyZPZCDwR8yAETcZQdE] last modified time of the note: 2021-02-09T16:13:46.666Z


[2021-03-01 01:17:15.168] [LOG]    [MMM-GoogleDocs-Notes][1b4hOQ64SilaMuivefAfcZjD7fYooHSPbn_Z3S_irvnM] last modified time of the note: 2021-02-10T09:44:35.340Z
```

But after about a week things goes sideways...
And it looks like this;

`[2021-03-02 09:41:12.171] [LOG]    [MMM-GoogleDocs-Notes] Failed to list the documents in your drive. The docs API returned an error: Error: invalid_grant`

I've googled it and it can be hundreds of different errors so thats why I'm asking here if anyone knows how to fix this for this specific module instead..
The only way of fixing this is to make a new 0Auth, but I would like to fix this so i don't need to make a new one every week.

Thanks for reading,
Niklas

**Comment by No3x** [comment] 2021-03-02 17:07
This sounds really annoying. I did not had this error myself since the creation of this module. But my token is from January 2020.

I did some research and found that a common cause for `Error: invalid_grant` is related to a password reset. Is this the case for you?
The error reason should yield a error in more detail within 12hours, after this it becomes the generic `invalid_grant` error message (which is not helpful). It would be good if you can find the error message in this time-span.

**Comment by No3x** [comment] 2021-03-02 17:12
Also please verify you created the token the right way (https://www.youtube.com/watch?v=BAHfqwAObag&feature=youtu.be)

**Comment by Niklas1191** [comment] 2021-03-03 08:39
Thanks for your reply,

I'm the sole user in this project, none else have access, no accounts have changed their permissions nor passwords.
I've also seen these solutions but not working for me.
Another reason can be system clock out of synch, but I've double checked that as well, not working.

Since it is basically 1 week of normal operations before the invalid_grant, i doubt it can be a human error, like revoking access.

One more note to mention; if I run the authorize.js cmd, it still say that it is authorized, but still get the invalid_grant.
The only way for me at this moment is to create a new 0Auth every week :(

**Comment by Niklas1191** [comment] 2021-03-03 08:43
There is alot of talk on the internet about a refresh token, does this module use it time to time?
If not, maybe that is the error?

The other thing i can think of is that there are no "Sonstige/Other" i can choose from, it seems google have changed their layout since your instruction, so i have tried both "TVs and Limited Input Devices" and "Universal Windows Platsform",

See picture included.

<img width="867" alt="Skärmavbild 2021-03-03 kl  09 39 37" src="https://user-images.githubusercontent.com/76033946/109778205-d3cbe300-7c04-11eb-9ddc-acc07d26ee1d.png">

**Comment by Niklas1191** [comment] 2021-03-03 08:46
According to the following link:  https://stackoverflow.com/questions/62528774/the-option-to-select-other-for-a-client-id-in-the-oauth-in-the-google-apis-is

The Desktop app is the new name for "Other".
Might be worth mentioning in your instructions.

I will try that one now and check back if it survives after a week.

**Comment by Niklas1191** [comment] 2021-03-03 08:56
The 0Auth is now refreshed using Desktop App, writing this for a timestamp log.
See you in a week ;)

**Comment by No3x** [comment] 2021-03-03 16:24
I have created a new token on a new project. I can confirm, that "Desktop" is the right choice. Furthermore I had to add my account as testuser to the "OAuth-Zustimmungsbildschirm" (or consent screen in english, I guess).

**Comment by Niklas1191** [comment] 2021-03-05 09:15
> I have created a new token on a new project. I can confirm, that "Desktop" is the right choice. Furthermore I had to add my account as testuser to the "OAuth-Zustimmungsbildschirm" (or consent screen in english, I guess).

What do you mean by adding you account as test user?
I only use one dedicated google-account for this project and the google account itself is not added anywhere in the rPi, am i missing something?

**Comment by Niklas1191** [comment] 2021-03-05 09:16
It say i have one test user and thats the account i use and is the owner of the project.

**Comment by Niklas1191** [comment] 2021-03-12 08:14
I'm back and checked my records.

Exactly a week after, there is an invalid_grant.

21-03-10 09:51:39 OK!
21-03-10 09:56:38 invalid_grant.....

No3x, The add user thing, I only have one account and thats the account i made the 0Auth with.
That one is added by default since it is a creator of the project. I don't think its what causes this. :(

**Comment by Niklas1191** [comment] 2021-03-12 08:49
Quickfix i need to do to get up and running again is the following:

remove the credentials file in /home/usr/.credentials
sudo -u pi -- node authorize.js
reconfirm my access and type in the access key and now it works again.

So apparently i don't need to remove and make a new 0Auth, but i have to reestablish the auth.
Is there a way to automate that or a way to not make google remove that after a week?

**Comment by No3x** [comment] 2021-03-14 15:59
I'm able to reproduce the issue with the tokens from https://github.com/No3x/MMM-GoogleDocs-Notes/issues/7#issuecomment-789840983. I was not able to reproduce the issue with my old token from 2020 - there is something special about it.

Are you still interested in a permanent fix? If so please tell me if you are experienced enough to change some lines in the code. I think I was not handling the refresh-tokens correctly.

**Comment by Niklas1191** [comment] 2021-03-15 12:49
> I'm able to reproduce the issue with the tokens from [#7 (comment)](https://github.com/No3x/MMM-GoogleDocs-Notes/issues/7#issuecomment-789840983). I was not able to reproduce the issue with my old token from 2020 - there is something special about it.
> 
> Are you still interested in a permanent fix? If so please tell me if you are experienced enough to change some lines in the code. I think I was not handling the refresh-tokens correctly but can offer a solution.

I have to admit that I'm not a good coder but I will do everything i can to sort this out!
If you're willing to help, I'd be very happy.

Do you have any email and i can send you code if you need it?

**Comment by No3x** [comment] 2021-03-15 19:33
Please locate the parts to add in the `node_helper.js` and add the green lines.
``` diff
       redirect_uris[0]
     );
 
+    oAuth2Client.on('tokens', this.storeToken);
+
     // Check if we have previously stored a token.
     fs.readFile(TOKEN_PATH, (err, token) => {
       if (err) return this.getNewToken(oAuth2Client, callback);
     });
   },
 
+  /**
+   * Store token to disk be used in later program executions.
+   *
+   * @param {Object} token The token to store to disk.
+   */
+  storeToken(token) {
+    try {
+      fs.mkdirSync(TOKEN_DIR);
+    } catch (err) {
+      if (err.code !== 'EEXIST') {
+        throw err;
+      }
+    }
+    fs.writeFileSync(TOKEN_PATH, JSON.stringify(token));
+    console.log(`Token stored to ${TOKEN_PATH}`);
+  },
   /**
    * Get and store new token after prompting for user authorization, and then
    * execute the given callback with the authorized OAuth2 client.
```
But without the `+` Signs. I added them here without them for easy copying them.
```node
 oAuth2Client.on('tokens', this.storeToken);
```
```node
  /**
   * Store token to disk be used in later program executions.
   *
   * @param {Object} token The token to store to disk.
   */
  storeToken(token) {
    try {
      fs.mkdirSync(TOKEN_DIR);
    } catch (err) {
      if (err.code !== 'EEXIST') {
        throw err;
      }
    }
    fs.writeFileSync(TOKEN_PATH, JSON.stringify(token));
    console.log(`Token stored to ${TOKEN_PATH}`);
  },
```

After this you might need to re-authenticate your client. Delete the `client_secret.json` and `MMM-GoogleDocs-Notes.json` and run `node authorize.js` again as usual.

**Comment by No3x** [comment] 2021-03-15 19:38
From time to time the log should contain`Token stored to ~/.credentials/MMM-GoogleDocs-Notes.json` - this is when a new token was created under the hood. This should fix the issue.

**Comment by No3x** [comment] 2021-03-15 22:16
I just got the same error again. The MMM-GoogleDocs-Notes.json does not contain the refresh_token in some circumstances which is required later in the process. I already try another solution. I think i just have to make sure the token is only overwritten if it contains the refresh token.

**Comment by Niklas1191** [comment] 2021-03-16 11:51
> I just got the same error again. The MMM-GoogleDocs-Notes.json does not contain the refresh_token in some circumstances which is required later in the process. I already try another solution. I think i just have to make sure the token is only overwritten if it contains the refresh token.

So should i wait with implementing your code untill you have tried out your second test?
I'm very happy you're helping me out with this, thanks alot for spending your time with this!

**Comment by No3x** [comment] 2021-03-16 17:31
> So should i wait with implementing your code untill you have tried out your second test?

Yes, this approach did not work yet.

Token works fine since yesterday so far. Waiting for a refresh_token occurrence now.

**Comment by No3x** [comment] 2021-03-16 17:37
If you want to test in parallel you can test with the changes explained above but the first segment a little diffrent:
```node
    oAuth2Client.on('tokens', (tokens) => {
      if (tokens.refresh_token) {
        console.log("Got new refresh token to store: " + tokens.refresh_token);
        this.storeToken(tokens);
      }
    });
```

**Comment by Niklas1191** [comment] 2021-03-18 09:28
Yeah, I'll test it out in parallel, rebooted with the new code now.
I'll keep monitoring the logs as well.

**Comment by Niklas1191** [comment] 2021-03-19 08:58
I have been testing for about 24 hours now. I did NOT refresh the credentials manually after i implemented your new code.

Now i got 09:42 OK and 09:47 invalid_grant.
Refreshing credentials manually now.

**Comment by No3x** [comment] 2021-03-19 17:27
For me it works fine so far with this variant:
```node
oAuth2Client.on('tokens', (tokens) => {
      if (tokens.refresh_token) {
        console.log(`>>refresh token<<<: ${tokens.refresh_token}`);
        this.storeToken(tokens);
        if (oAuth2Client) oAuth2Client.setCredentials(tokens);
      }
      console.log(`>>new token<<<`);
    });
```
The old one might work too. You can test the old one and I stay with this for some days.

**Comment by Niklas1191** [comment] 2021-03-22 08:37
Okay, Ill stick with this one:

```
    oAuth2Client.on('tokens', (tokens) => {
      if (tokens.refresh_token) {
        console.log("Got new refresh token to store: " + tokens.refresh_token);
        this.storeToken(tokens);
      }
    });
```

**Comment by No3x** [comment] 2021-03-25 17:43
I made some changes to the token handling. The key point is the merging of old and new token information so that the refresh_token get's updated. 
Please try this branch: https://github.com/No3x/MMM-GoogleDocs-Notes/tree/bug/invalid_grant

**Comment by Niklas1191** [comment] 2021-03-26 08:04
> I made some changes to the token handling. The key point is the merging of old and new token information so that the refresh_token get's updated.
> Please try this branch: https://github.com/No3x/MMM-GoogleDocs-Notes/tree/bug/invalid_grant

Thank you!

I'm not very familiar with git, what are the proper cmd for merging the new files from that branch?

**Comment by No3x** [comment] 2021-03-29 16:50
You can download the branch with this link:
https://github.com/No3x/MMM-GoogleDocs-Notes/zipball/bug/invalid_grant

**Comment by No3x** [comment] 2021-03-29 16:51
Or if you already have the repository 
```
git fetch
git checkout bug/invalid_grant
```

**Comment by Niklas1191** [comment] 2021-03-30 08:07
Doesn't seem to work properly.

`[2021-03-30 10:04:22.066] [LOG]    Launching application.`

Any ideas?

**Comment by Niklas1191** [comment] 2021-03-31 08:03
Yes i did, but I never did npm install, maybe that’s what’s wrong..

**Comment by No3x** [comment] 2021-03-31 22:19
Yes, npm i should be required too, since I added a new dependency. I would have expected a better error message though.

**Comment by Niklas1191** [comment] 2021-04-01 07:46
My bad, its worked out.
Looking good my friend!

```
[2021-04-01 09:45:25.094] [LOG]    [MMM-GoogleDocs-Notes] loading token from '/home/pi/.credentials/MMM-GoogleDocs-Notes.json'
[2021-04-01 09:45:25.103] [LOG]    [MMM-GoogleDocs-Notes] Storing token to '/home/pi/.credentials/MMM-GoogleDocs-Notes.json'

```

**Comment by No3x** [comment] 2021-04-01 15:55
I just started MMM after some days and receive invalid_grant again. But maybe it works if you do not turn off MMM so long.

**Comment by Niklas1191** [comment] 2021-04-01 17:30
Okay, well I’m still testing, went to the new version not long ago and mine is online 24/7.

I will give you an update next week, happy easter!

**Comment by Niklas1191** [comment] 2021-04-06 06:59
Good morning,

I just had an invalid_grant when i got back to work.
Did a manual re-auth by removing the file in .credentials and re auth.

Trying again.

**Comment by Niklas1191** [comment] 2021-04-06 08:31
```
[2021-04-06 09:00:49.404] [LOG]    [MMM-GoogleDocs-Notes] loading client secret from '/home/pi/MagicMirror/modules/MMM-GoogleDocs-Notes/client_secret.json'
[2021-04-06 09:00:49.410] [LOG]    [MMM-GoogleDocs-Notes] loading token from '/home/pi/.credentials/MMM-GoogleDocs-Notes.json'
[2021-04-06 09:00:49.415] [LOG]    [MMM-GoogleDocs-Notes] getNoteData
```

Shouldn't there be any "Refreshing token" somewhere?

**Comment by No3x** [comment] 2021-04-09 15:41
I have upgraded the `google-api` dependency to the latest version. Please try the new version and make sure to delete `node_modules` directory and execute `npm i` afterwards. Maybe this does something..
I have also enabled some debug statements so that we should see
```
[MMM-GoogleDocs-Notes] new tokens: 
```
From time to time.

**Comment by Niklas1191** [comment] 2021-04-12 10:53
Since I'm not that great on GIT, this is what i did after i removed the old node_modules folder, Git fetch and Git pull, then npm install. I should be in the proper tree.
It is up and running again, waiting to see the new debug info.

**Comment by No3x** [comment] 2021-04-12 17:54
That sounds like the right steps.

**Comment by Niklas1191** [comment] 2021-04-13 12:10
Got the invalid_grant error today, created a new auth manually and trying again.

**Comment by Niklas1191** [comment] 2021-04-20 15:01
Yep, still got the invalid_grant. But i see no new log messages you told me you added. Have i done something wrong perhaps?

**Comment by No3x** [comment] 2021-04-20 21:15
Please post the output of `git log` for a quick view or check [the changes manually I was referring to](https://github.com/No3x/MMM-GoogleDocs-Notes/commit/b4d06dbe6c8a96aa12c671df01fd7d01e232141e). 

I also got invalid_grant after some time. I don't have an idea but there are some issues on the googleapis/google-auth-library-nodejs (esp. https://github.com/googleapis/google-auth-library-nodejs/issues/1093) repository about invalid_grant issues but I'm not sure if they are related.

**Comment by Niklas1191** [comment] 2021-04-21 07:35
Yeah, the change is there.
Back to square one it seems.

Well, I'll buy you a beer if you find a workaround ;)

**Comment by No3x** [comment] 2021-04-28 20:10
I found a similar issue here https://community.openhab.org/t/google-nest-device-access-console-now-available/105404/241
The reason seems to be that the app must be in production mode. I just checked it but it already was in production mode for me but I don't know since when. Back in March it was in test modus (see https://github.com/No3x/MMM-GoogleDocs-Notes/issues/7#issuecomment-792933435) Switched from prod -> test -> prod and try again.

**Comment by Niklas1191** [comment] 2021-04-29 06:13
Thanks for your idea, mine was in testing, i just changed to production.
Do you think i should remove the file in .credentials and re-auth again or just leave it?

**Comment by No3x** [comment] 2021-05-06 19:33
8 days and it's working fine so far. 👍🏻

**Comment by Niklas1191** [comment] 2021-05-07 06:19
> 8 days and it's working fine so far. 👍🏻

I had an invalid_grant but I kept the old token after i made the production change so I'll try one more week with a refreshed one and see if I still get the bad result before scream its not working :)

**Comment by Niklas1191** [comment] 2021-05-18 06:29
No3x, I'm now up in 11 days and still going without invalid_grant!
I think your solution worked! So where do i send that beer? ;)

**Comment by ssy21** [comment] 2021-05-29 20:14
> !
hey I'm having this same issue with mmm-googledocs-notes, so did you just have to change to production and make a new token? did you not need the code pasted from above?

**Comment by ssy21** [comment] 2021-05-29 20:15
> No3x, I'm now up in 11 days and still going without invalid_grant!
> I think your solution worked! So where do i send that beer? ;)
hey I'm running into the same issue with mmm-googledocs-notes, did you just change to production and make a new token? was that all that was necessary? or did you add that code pasted above also?

**Comment by ssy21** [comment] 2021-05-29 20:16
> No3x, I'm now up in 11 days and still going without invalid_grant!
> I think your solution worked! So where do i send that beer? ;)

hey I'm running into the same issue with mmm-googledocs-notes, did you just change to production and make a new token? was that all that was necessary? or did you add that code pasted above also?

**Comment by No3x** [comment] 2021-05-29 20:44
@ssy21 The change to production and a new token should be sufficient. Please test it.

**Comment by No3x** [comment] 2021-05-29 20:48
> So where do i send that beer? ;)

@Niklas1191 what kind of beer we are talking about? Can it be better than german beer? In general you are free to donate to my FOSS fund on my website no3x.de.

**Comment by ssy21** [comment] 2021-05-29 21:08
> @ssy21 The change to production and a new token should be sufficient. Please test it.

still getting the invalid_grant error, by generating a new token we mean to create a brand new oauth id right? and then put the new client secret json file inside the mmm-googledocs-notes folder?

**Comment by No3x** [comment] 2021-05-29 21:19
Please delete the token from the .credentials directory in your user directory and run the authorize process again.

**Comment by ssy21** [comment] 2021-05-30 19:39
> Please delete the token from the .credentials directory in your user directory and run the authorize process again.

I looked in my home/usr for the credentials file but I don't see anything like that in that directory

**Comment by ssy21** [comment] 2021-05-30 19:50
oh okay actually so I was supposed to go to home/pi (instead of usr, pi is my user name) but I still couldn't find the directory, but so instead I just did rmdir ~/.credentials and that seemed to work, doing reauth step now

**Comment by ssy21** [comment] 2021-05-30 19:53
it's working again, I'll let you know if it works after more than a week!

**Comment by No3x** [comment] 2021-05-30 20:24
Yes, i meant `~/.credentials`. FYI: `.`-directories are hidden in most fs explorers. Use `ls -la` to show them.

**Comment by ssy21** [comment] 2021-05-30 21:50
> Yes, i meant `~/.credentials`. FYI: `.`-directories are hidden in most fs explorers. Use `ls -la` to show them.

this is off topic, but is there a way to show a notification such as an image or gif where a new update has been made to the google doc?

**Comment by No3x** [comment] 2021-05-30 22:02
The docs are polled at a fix interval and there is no tracking of new/old/changed docs. So I guess this is not possible yet and I'm not planning to add it myself.

**Comment by ssy21** [comment] 2021-05-30 22:17
> The docs are polled at a fix interval and there is no tracking of new/old/changed docs. So I guess this is not possible yet and I'm not planning to add it myself.
> But it should be easy to implement in the node_helper.js by saving a map of the doc#ids's and the modification timestamp and sending a new event over the socket (`sendSocketNotification`) when something changed. Then the MMM-GoogleDocs-Notes.js can register for that event in the ` socketNotificationReceived` and show a gif.

what you said makes decent sense, but implementing it would be the hard part for me. looking at the code, in the node_helper.js file, does the { data: notes } contain the doc id's and timestamp? would I just be able to use the timestamp by itself and so we save the timestamp and then next time it checks, if the timestamp is different, send a new event?

**Comment by No3x** [comment] 2021-05-30 22:30
> file, does the { data: notes } contain the doc id's and timestamp?


Yes, notes is in array and each entry consists of the attributes
```javascript
noteText,
dateStamp (modifiedTime)
```

> would I just be able to use the timestamp by itself and so we save the timestamp and then next time it checks, if the timestamp is different, send a new event?

Yes this logic should work. For this you need to change the scope of the notes variable (e.g. a global variable) so that you keep the information between the function calls (but actually I'm not sure if the node_helper is created every time in the interval -> you should check this first).

**Comment by Niklas1191** [comment] 2021-06-01 06:45
> > So where do i send that beer? ;)
> 
> @Niklas1191 what kind of beer we are talking about? Can it be better than german beer? In general you are free to donate to my FOSS fund on my website no3x.de.

Nothing beats german beer, and it bugs me that none imports Krombacher to Sweden....
Anyways, I tried your donation button but it sends me to a blank page, I'll try tomorrow ;)

And again, thanks for helping out on this issue, everything works perfect!

**Comment by No3x** [comment] 2021-06-10 17:56
@Niklas1191 I think I have fixed the donation page.

**Comment by Niklas1191** [comment] 2021-06-11 07:27
> @Niklas1191 I think I have fixed the donation page.

Nope, after i click the donate-button it says: "Access Denied. See Seamless Donations log for details.".
Not so "seamless" right now ;)

While typing here, just writing 2 random requests if you have the time and are intrested.

* Config option to have documents list sidebyside instead of underneath eachother
* Fix resizing issue if you have a jpg/png in a document. Now it doesnt appear to show pictures in the same format as they are in a document, it makes it very big and missplaced, i assume this is because it cannot understand the formating in the document. Same goes for blank rows in the text, but it works by having a space character in the row.

**Comment by No3x** [comment] 2021-06-11 16:22
I was able to reproduce the error after some tries. It worked fine one multiple devices yesterday though. It should be fixed now.
You can create issues and elaborate what you want to archive. It's easier for people that want to contribute.

**Comment by ssy21** [comment] 2021-06-12 12:52
just checked the google docs module today and it's still going past 7 days! thanks!

**Comment by Niklas1191** [comment] 2021-06-14 07:59
> just checked the google docs module today and it's still going past 7 days! thanks!

Thats great!
I guess that we could close this issue then :)

**Closed** 2021-06-14 07:59 UTC
